package com.team2052.frckrawler.core.data.models;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TEAM".
 */
@Entity
public class Team implements java.io.Serializable {

    @Id
    @Unique
    private Long number;

    @Unique
    private String teamkey;
    private String name;
    private String data;
    private java.util.Date last_updated;
    private String comments;

    @Generated
    public Team() {
    }

    public Team(Long number) {
        this.number = number;
    }

    @Generated
    public Team(Long number, String teamkey, String name, String data, java.util.Date last_updated, String comments) {
        this.number = number;
        this.teamkey = teamkey;
        this.name = name;
        this.data = data;
        this.last_updated = last_updated;
        this.comments = comments;
    }

    public Long getNumber() {
        return number;
    }

    public void setNumber(Long number) {
        this.number = number;
    }

    public String getTeamkey() {
        return teamkey;
    }

    public void setTeamkey(String teamkey) {
        this.teamkey = teamkey;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public java.util.Date getLast_updated() {
        return last_updated;
    }

    public void setLast_updated(java.util.Date last_updated) {
        this.last_updated = last_updated;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

}
