package com.team2052.frckrawler.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF390000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF6F1008)
val onPrimaryContainerLight = Color(0xFFFFB5A9)
val secondaryLight = Color(0xFF775A00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFCD4E)
val onSecondaryContainerLight = Color(0xFF503C00)
val tertiaryLight = Color(0xFF775A00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFCD4E)
val onTertiaryContainerLight = Color(0xFF503C00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF241917)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF241917)
val surfaceVariantLight = Color(0xFFFCDBD6)
val onSurfaceVariantLight = Color(0xFF57423E)
val outlineLight = Color(0xFF8B716D)
val outlineVariantLight = Color(0xFFDEC0BB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3A2D2B)
val inverseOnSurfaceLight = Color(0xFFFFEDEA)
val inversePrimaryLight = Color(0xFFFFB4A8)
val surfaceDimLight = Color(0xFFEBD5D2)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0EE)
val surfaceContainerLight = Color(0xFFFFE9E6)
val surfaceContainerHighLight = Color(0xFFF9E3E0)
val surfaceContainerHighestLight = Color(0xFFF4DEDA)

val primaryDark = Color(0xFFFFB4A8)
val onPrimaryDark = Color(0xFF660803)
val primaryContainerDark = Color(0xFF4C0000)
val onPrimaryContainerDark = Color(0xFFFF8B7A)
val secondaryDark = Color(0xFFFFF1D8)
val onSecondaryDark = Color(0xFF3F2E00)
val secondaryContainerDark = Color(0xFFF9BF00)
val onSecondaryContainerDark = Color(0xFF473400)
val tertiaryDark = Color(0xFFFFF1D8)
val onTertiaryDark = Color(0xFF3F2E00)
val tertiaryContainerDark = Color(0xFFF9BF00)
val onTertiaryContainerDark = Color(0xFF473400)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1B110F)
val onBackgroundDark = Color(0xFFF4DEDA)
val surfaceDark = Color(0xFF1B110F)
val onSurfaceDark = Color(0xFFF4DEDA)
val surfaceVariantDark = Color(0xFF57423E)
val onSurfaceVariantDark = Color(0xFFDEC0BB)
val outlineDark = Color(0xFFA68A86)
val outlineVariantDark = Color(0xFF57423E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF4DEDA)
val inverseOnSurfaceDark = Color(0xFF3A2D2B)
val inversePrimaryDark = Color(0xFFA7392B)
val surfaceDimDark = Color(0xFF1B110F)
val surfaceBrightDark = Color(0xFF443634)
val surfaceContainerLowestDark = Color(0xFF160C0A)
val surfaceContainerLowDark = Color(0xFF241917)
val surfaceContainerDark = Color(0xFF291D1B)
val surfaceContainerHighDark = Color(0xFF342725)
val surfaceContainerHighestDark = Color(0xFF3F3230)




