package com.team2052.frckrawler.ui.theme
import androidx.compose.ui.graphics.Color

object StaticColors {
  val onSuccess = Color(0xFF7ca873)
  val successContainer = Color(0xFF226f08)
}

val primaryLight = Color(0xFF390000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF6F1008)
val onPrimaryContainerLight = Color(0xFFFFB5A9)
val secondaryLight = Color(0xFF775A00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFCD4E)
val onSecondaryContainerLight = Color(0xFF503C00)
val tertiaryLight = Color(0xFF775A00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFCD4E)
val onTertiaryContainerLight = Color(0xFF503C00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF241917)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF241917)
val surfaceVariantLight = Color(0xFFFCDBD6)
val onSurfaceVariantLight = Color(0xFF57423E)
val outlineLight = Color(0xFF8B716D)
val outlineVariantLight = Color(0xFFDEC0BB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3A2D2B)
val inverseOnSurfaceLight = Color(0xFFFFEDEA)
val inversePrimaryLight = Color(0xFFFFB4A8)
val surfaceDimLight = Color(0xFFEBD5D2)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0EE)
val surfaceContainerLight = Color(0xFFFFE9E6)
val surfaceContainerHighLight = Color(0xFFF9E3E0)
val surfaceContainerHighestLight = Color(0xFFF4DEDA)


val primaryDark = Color(0xFFE7C26C)
val onPrimaryDark = Color(0xFF3F2E00)
val primaryContainerDark = Color(0xFF5A4300)
val onPrimaryContainerDark = Color(0xFFFFDF99)
val secondaryDark = Color(0xFFFFB4A8)
val onSecondaryDark = Color(0xFF561E17)
val secondaryContainerDark = Color(0xFF73342B)
val onSecondaryContainerDark = Color(0xFFFFDAD4)
val tertiaryDark = Color(0xFFE7C26C)
val onTertiaryDark = Color(0xFF3F2E00)
val tertiaryContainerDark = Color(0xFF5A4300)
val onTertiaryContainerDark = Color(0xFFFFDF99)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF17130B)
val onBackgroundDark = Color(0xFFEBE1D4)
val surfaceDark = Color(0xFF17130B)
val onSurfaceDark = Color(0xFFEBE1D4)
val surfaceVariantDark = Color(0xFF4D4639)
val onSurfaceVariantDark = Color(0xFFD0C5B4)
val outlineDark = Color(0xFF999080)
val outlineVariantDark = Color(0xFF4D4639)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEBE1D4)
val inverseOnSurfaceDark = Color(0xFF353027)
val inversePrimaryDark = Color(0xFF765A0B)
val surfaceDimDark = Color(0xFF17130B)
val surfaceBrightDark = Color(0xFF3E392F)
val surfaceContainerLowestDark = Color(0xFF110E07)
val surfaceContainerLowDark = Color(0xFF1F1B13)
val surfaceContainerDark = Color(0xFF231F17)
val surfaceContainerHighDark = Color(0xFF2E2921)
val surfaceContainerHighestDark = Color(0xFF39342B)
