package com.team2052.frckrawler.models;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teamDaoConfig;
    private final DaoConfig metricDaoConfig;
    private final DaoConfig matchDatumDaoConfig;
    private final DaoConfig matchCommentDaoConfig;
    private final DaoConfig pitDatumDaoConfig;
    private final DaoConfig serverLogEntryDaoConfig;

    private final TeamDao teamDao;
    private final MetricDao metricDao;
    private final MatchDatumDao matchDatumDao;
    private final MatchCommentDao matchCommentDao;
    private final PitDatumDao pitDatumDao;
    private final ServerLogEntryDao serverLogEntryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teamDaoConfig = daoConfigMap.get(TeamDao.class).clone();
        teamDaoConfig.initIdentityScope(type);

        metricDaoConfig = daoConfigMap.get(MetricDao.class).clone();
        metricDaoConfig.initIdentityScope(type);

        matchDatumDaoConfig = daoConfigMap.get(MatchDatumDao.class).clone();
        matchDatumDaoConfig.initIdentityScope(type);

        matchCommentDaoConfig = daoConfigMap.get(MatchCommentDao.class).clone();
        matchCommentDaoConfig.initIdentityScope(type);

        pitDatumDaoConfig = daoConfigMap.get(PitDatumDao.class).clone();
        pitDatumDaoConfig.initIdentityScope(type);

        serverLogEntryDaoConfig = daoConfigMap.get(ServerLogEntryDao.class).clone();
        serverLogEntryDaoConfig.initIdentityScope(type);

        teamDao = new TeamDao(teamDaoConfig, this);
        metricDao = new MetricDao(metricDaoConfig, this);
        matchDatumDao = new MatchDatumDao(matchDatumDaoConfig, this);
        matchCommentDao = new MatchCommentDao(matchCommentDaoConfig, this);
        pitDatumDao = new PitDatumDao(pitDatumDaoConfig, this);
        serverLogEntryDao = new ServerLogEntryDao(serverLogEntryDaoConfig, this);

        registerDao(Team.class, teamDao);
        registerDao(Metric.class, metricDao);
        registerDao(MatchDatum.class, matchDatumDao);
        registerDao(MatchComment.class, matchCommentDao);
        registerDao(PitDatum.class, pitDatumDao);
        registerDao(ServerLogEntry.class, serverLogEntryDao);
    }

    public void clear() {
        teamDaoConfig.clearIdentityScope();
        metricDaoConfig.clearIdentityScope();
        matchDatumDaoConfig.clearIdentityScope();
        matchCommentDaoConfig.clearIdentityScope();
        pitDatumDaoConfig.clearIdentityScope();
        serverLogEntryDaoConfig.clearIdentityScope();
    }

    public TeamDao getTeamDao() {
        return teamDao;
    }

    public MetricDao getMetricDao() {
        return metricDao;
    }

    public MatchDatumDao getMatchDatumDao() {
        return matchDatumDao;
    }

    public MatchCommentDao getMatchCommentDao() {
        return matchCommentDao;
    }

    public PitDatumDao getPitDatumDao() {
        return pitDatumDao;
    }

    public ServerLogEntryDao getServerLogEntryDao() {
        return serverLogEntryDao;
    }

}
