package com.team2052.frckrawler.models;

import org.greenrobot.greendao.annotation.*;

import java.util.List;

import com.team2052.frckrawler.models.DaoSession;

import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "EVENT".
 */
@Entity(active = true)
public class Event implements java.io.Serializable {

    @Id
    private Long id;

    @Unique
    private String fmsid;
    private String name;
    private long season_id;
    private String data;
    private java.util.Date date;
    private String unique_hash;

    /**
     * Used to resolve relations
     */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient EventDao myDao;

    @ToOne(joinProperty = "season_id")
    private Season season;

    @Generated
    private transient Long season__resolvedKey;

    @ToMany(joinProperties = {
            @JoinProperty(name = "id", referencedName = "event_id")
    })
    private List<MatchComment> matchCommentList;

    @ToMany(joinProperties = {
            @JoinProperty(name = "id", referencedName = "event_id")
    })
    private List<RobotEvent> robotEventList;

    @ToMany(joinProperties = {
            @JoinProperty(name = "id", referencedName = "event_id")
    })
    private List<MatchDatum> matchDatumList;

    @ToMany(joinProperties = {
            @JoinProperty(name = "id", referencedName = "event_id")
    })
    private List<PitDatum> pitDatumList;

    @Generated
    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    @Generated
    public Event(Long id, String fmsid, String name, long season_id, String data, java.util.Date date, String unique_hash) {
        this.id = id;
        this.fmsid = fmsid;
        this.name = name;
        this.season_id = season_id;
        this.data = data;
        this.date = date;
        this.unique_hash = unique_hash;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEventDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFmsid() {
        return fmsid;
    }

    public void setFmsid(String fmsid) {
        this.fmsid = fmsid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getSeason_id() {
        return season_id;
    }

    public void setSeason_id(long season_id) {
        this.season_id = season_id;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getUnique_hash() {
        return unique_hash;
    }

    public void setUnique_hash(String unique_hash) {
        this.unique_hash = unique_hash;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Season getSeason() {
        long __key = this.season_id;
        if (season__resolvedKey == null || !season__resolvedKey.equals(__key)) {
            __throwIfDetached();
            SeasonDao targetDao = daoSession.getSeasonDao();
            Season seasonNew = targetDao.load(__key);
            synchronized (this) {
                season = seasonNew;
                season__resolvedKey = __key;
            }
        }
        return season;
    }

    @Generated
    public void setSeason(Season season) {
        if (season == null) {
            throw new DaoException("To-one property 'season_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.season = season;
            season_id = season.getId();
            season__resolvedKey = season_id;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<MatchComment> getMatchCommentList() {
        if (matchCommentList == null) {
            __throwIfDetached();
            MatchCommentDao targetDao = daoSession.getMatchCommentDao();
            List<MatchComment> matchCommentListNew = targetDao._queryEvent_MatchCommentList(id);
            synchronized (this) {
                if (matchCommentList == null) {
                    matchCommentList = matchCommentListNew;
                }
            }
        }
        return matchCommentList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetMatchCommentList() {
        matchCommentList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<RobotEvent> getRobotEventList() {
        if (robotEventList == null) {
            __throwIfDetached();
            RobotEventDao targetDao = daoSession.getRobotEventDao();
            List<RobotEvent> robotEventListNew = targetDao._queryEvent_RobotEventList(id);
            synchronized (this) {
                if (robotEventList == null) {
                    robotEventList = robotEventListNew;
                }
            }
        }
        return robotEventList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetRobotEventList() {
        robotEventList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<MatchDatum> getMatchDatumList() {
        if (matchDatumList == null) {
            __throwIfDetached();
            MatchDatumDao targetDao = daoSession.getMatchDatumDao();
            List<MatchDatum> matchDatumListNew = targetDao._queryEvent_MatchDatumList(id);
            synchronized (this) {
                if (matchDatumList == null) {
                    matchDatumList = matchDatumListNew;
                }
            }
        }
        return matchDatumList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetMatchDatumList() {
        matchDatumList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<PitDatum> getPitDatumList() {
        if (pitDatumList == null) {
            __throwIfDetached();
            PitDatumDao targetDao = daoSession.getPitDatumDao();
            List<PitDatum> pitDatumListNew = targetDao._queryEvent_PitDatumList(id);
            synchronized (this) {
                if (pitDatumList == null) {
                    pitDatumList = pitDatumListNew;
                }
            }
        }
        return pitDatumList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetPitDatumList() {
        pitDatumList = null;
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
     * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
     * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
     * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
