package com.team2052.frckrawler.models;

import org.greenrobot.greendao.DaoException;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.ToOne;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MATCH_DATUM".
 */
@Entity(active = true)
public class MatchDatum implements java.io.Serializable {

    @Id
    private Long id;
    private long team_id;
    private long metric_id;
    private int match_type;
    private long match_number;
    private java.util.Date last_updated;
    private String data;

    /**
     * Used to resolve relations
     */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient MatchDatumDao myDao;

    @ToOne(joinProperty = "team_id")
    private Team team;

    @Generated
    private transient Long team__resolvedKey;

    @ToOne(joinProperty = "metric_id")
    private Metric metric;

    @Generated
    private transient Long metric__resolvedKey;

    @Generated
    public MatchDatum() {
    }

    public MatchDatum(Long id) {
        this.id = id;
    }

    @Generated
    public MatchDatum(Long id, long team_id, long metric_id, int match_type, long match_number, java.util.Date last_updated, String data) {
        this.id = id;
        this.team_id = team_id;
        this.metric_id = metric_id;
        this.match_type = match_type;
        this.match_number = match_number;
        this.last_updated = last_updated;
        this.data = data;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMatchDatumDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTeam_id() {
        return team_id;
    }

    public void setTeam_id(long team_id) {
        this.team_id = team_id;
    }

    public long getMetric_id() {
        return metric_id;
    }

    public void setMetric_id(long metric_id) {
        this.metric_id = metric_id;
    }

    public int getMatch_type() {
        return match_type;
    }

    public void setMatch_type(int match_type) {
        this.match_type = match_type;
    }

    public long getMatch_number() {
        return match_number;
    }

    public void setMatch_number(long match_number) {
        this.match_number = match_number;
    }

    public java.util.Date getLast_updated() {
        return last_updated;
    }

    public void setLast_updated(java.util.Date last_updated) {
        this.last_updated = last_updated;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Team getTeam() {
        long __key = this.team_id;
        if (team__resolvedKey == null || !team__resolvedKey.equals(__key)) {
            __throwIfDetached();
            TeamDao targetDao = daoSession.getTeamDao();
            Team teamNew = targetDao.load(__key);
            synchronized (this) {
                team = teamNew;
                team__resolvedKey = __key;
            }
        }
        return team;
    }

    @Generated
    public void setTeam(Team team) {
        if (team == null) {
            throw new DaoException("To-one property 'team_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.team = team;
            team_id = team.getNumber();
            team__resolvedKey = team_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Metric getMetric() {
        long __key = this.metric_id;
        if (metric__resolvedKey == null || !metric__resolvedKey.equals(__key)) {
            __throwIfDetached();
            MetricDao targetDao = daoSession.getMetricDao();
            Metric metricNew = targetDao.load(__key);
            synchronized (this) {
                metric = metricNew;
                metric__resolvedKey = __key;
            }
        }
        return metric;
    }

    @Generated
    public void setMetric(Metric metric) {
        if (metric == null) {
            throw new DaoException("To-one property 'metric_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.metric = metric;
            metric_id = metric.getId();
            metric__resolvedKey = metric_id;
        }
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
     * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
     * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
     * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
