package com.team2052.frckrawler.models;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "MATCH_DATUM".
 */
public class MatchDatumDao extends AbstractDao<MatchDatum, Long> {

    public static final String TABLENAME = "MATCH_DATUM";
    private DaoSession daoSession;
    private Query<MatchDatum> event_MatchDatumListQuery;
    private Query<MatchDatum> robot_MatchDatumListQuery;
    private Query<MatchDatum> metric_MatchDatumListQuery;
    private String selectDeep;

    public MatchDatumDao(DaoConfig config) {
        super(config);
    }

    public MatchDatumDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MATCH_DATUM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"EVENT_ID\" INTEGER NOT NULL ," + // 1: event_id
                "\"ROBOT_ID\" INTEGER NOT NULL ," + // 2: robot_id
                "\"METRIC_ID\" INTEGER NOT NULL ," + // 3: metric_id
                "\"MATCH_TYPE\" INTEGER NOT NULL ," + // 4: match_type
                "\"MATCH_NUMBER\" INTEGER NOT NULL ," + // 5: match_number
                "\"LAST_UPDATED\" INTEGER," + // 6: last_updated
                "\"DATA\" TEXT);"); // 7: data
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MATCH_DATUM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MatchDatum entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEvent_id());
        stmt.bindLong(3, entity.getRobot_id());
        stmt.bindLong(4, entity.getMetric_id());
        stmt.bindLong(5, entity.getMatch_type());
        stmt.bindLong(6, entity.getMatch_number());
 
        java.util.Date last_updated = entity.getLast_updated();
        if (last_updated != null) {
            stmt.bindLong(7, last_updated.getTime());
        }
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(8, data);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MatchDatum entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEvent_id());
        stmt.bindLong(3, entity.getRobot_id());
        stmt.bindLong(4, entity.getMetric_id());
        stmt.bindLong(5, entity.getMatch_type());
        stmt.bindLong(6, entity.getMatch_number());
 
        java.util.Date last_updated = entity.getLast_updated();
        if (last_updated != null) {
            stmt.bindLong(7, last_updated.getTime());
        }
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(8, data);
        }
    }

    @Override
    protected final void attachEntity(MatchDatum entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MatchDatum readEntity(Cursor cursor, int offset) {
        MatchDatum entity = new MatchDatum( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // event_id
                cursor.getLong(offset + 2), // robot_id
                cursor.getLong(offset + 3), // metric_id
                cursor.getInt(offset + 4), // match_type
                cursor.getLong(offset + 5), // match_number
                cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // last_updated
                cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // data
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MatchDatum entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEvent_id(cursor.getLong(offset + 1));
        entity.setRobot_id(cursor.getLong(offset + 2));
        entity.setMetric_id(cursor.getLong(offset + 3));
        entity.setMatch_type(cursor.getInt(offset + 4));
        entity.setMatch_number(cursor.getLong(offset + 5));
        entity.setLast_updated(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setData(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MatchDatum entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MatchDatum entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MatchDatum entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

    /** Internal query to resolve the "matchDatumList" to-many relationship of Event. */
    public List<MatchDatum> _queryEvent_MatchDatumList(long event_id) {
        synchronized (this) {
            if (event_MatchDatumListQuery == null) {
                QueryBuilder<MatchDatum> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Event_id.eq(null));
                event_MatchDatumListQuery = queryBuilder.build();
            }
        }
        Query<MatchDatum> query = event_MatchDatumListQuery.forCurrentThread();
        query.setParameter(0, event_id);
        return query.list();
    }

    /** Internal query to resolve the "matchDatumList" to-many relationship of Robot. */
    public List<MatchDatum> _queryRobot_MatchDatumList(long robot_id) {
        synchronized (this) {
            if (robot_MatchDatumListQuery == null) {
                QueryBuilder<MatchDatum> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Robot_id.eq(null));
                robot_MatchDatumListQuery = queryBuilder.build();
            }
        }
        Query<MatchDatum> query = robot_MatchDatumListQuery.forCurrentThread();
        query.setParameter(0, robot_id);
        return query.list();
    }

    /** Internal query to resolve the "matchDatumList" to-many relationship of Metric. */
    public List<MatchDatum> _queryMetric_MatchDatumList(long metric_id) {
        synchronized (this) {
            if (metric_MatchDatumListQuery == null) {
                QueryBuilder<MatchDatum> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Metric_id.eq(null));
                metric_MatchDatumListQuery = queryBuilder.build();
            }
        }
        Query<MatchDatum> query = metric_MatchDatumListQuery.forCurrentThread();
        query.setParameter(0, metric_id);
        return query.list();
    }

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEventDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getRobotDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getMetricDao().getAllColumns());
            builder.append(" FROM MATCH_DATUM T");
            builder.append(" LEFT JOIN EVENT T0 ON T.\"EVENT_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN ROBOT T1 ON T.\"ROBOT_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN METRIC T2 ON T.\"METRIC_ID\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected MatchDatum loadCurrentDeep(Cursor cursor, boolean lock) {
        MatchDatum entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Event event = loadCurrentOther(daoSession.getEventDao(), cursor, offset);
        if (event != null) {
            entity.setEvent(event);
        }
        offset += daoSession.getEventDao().getAllColumns().length;

        Robot robot = loadCurrentOther(daoSession.getRobotDao(), cursor, offset);
        if (robot != null) {
            entity.setRobot(robot);
        }
        offset += daoSession.getRobotDao().getAllColumns().length;

        Metric metric = loadCurrentOther(daoSession.getMetricDao(), cursor, offset);
        if (metric != null) {
            entity.setMetric(metric);
        }

        return entity;
    }
    
    public MatchDatum loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[]{key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MatchDatum> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MatchDatum> list = new ArrayList<MatchDatum>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MatchDatum> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MatchDatum> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
    
    /**
     * Properties of entity MatchDatum.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Event_id = new Property(1, long.class, "event_id", false, "EVENT_ID");
        public final static Property Robot_id = new Property(2, long.class, "robot_id", false, "ROBOT_ID");
        public final static Property Metric_id = new Property(3, long.class, "metric_id", false, "METRIC_ID");
        public final static Property Match_type = new Property(4, int.class, "match_type", false, "MATCH_TYPE");
        public final static Property Match_number = new Property(5, long.class, "match_number", false, "MATCH_NUMBER");
        public final static Property Last_updated = new Property(6, java.util.Date.class, "last_updated", false, "LAST_UPDATED");
        public final static Property Data = new Property(7, String.class, "data", false, "DATA");
    }
 
}
