package com.team2052.frckrawler.models;

import org.greenrobot.greendao.DaoException;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.ToOne;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MATCH_COMMENT".
 */
@Entity(active = true)
public class MatchComment implements java.io.Serializable {

    @Id
    private Long id;
    private Long match_number;
    private Integer match_type;
    private Long robot_id;
    private Long event_id;
    private String comment;
    private java.util.Date last_updated;

    /**
     * Used to resolve relations
     */
    @Generated
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    @Generated
    private transient MatchCommentDao myDao;

    @ToOne(joinProperty = "robot_id")
    private Robot robot;

    @Generated
    private transient Long robot__resolvedKey;

    @ToOne(joinProperty = "event_id")
    private Event event;

    @Generated
    private transient Long event__resolvedKey;

    @Generated
    public MatchComment() {
    }

    public MatchComment(Long id) {
        this.id = id;
    }

    @Generated
    public MatchComment(Long id, Long match_number, Integer match_type, Long robot_id, Long event_id, String comment, java.util.Date last_updated) {
        this.id = id;
        this.match_number = match_number;
        this.match_type = match_type;
        this.robot_id = robot_id;
        this.event_id = event_id;
        this.comment = comment;
        this.last_updated = last_updated;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMatchCommentDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMatch_number() {
        return match_number;
    }

    public void setMatch_number(Long match_number) {
        this.match_number = match_number;
    }

    public Integer getMatch_type() {
        return match_type;
    }

    public void setMatch_type(Integer match_type) {
        this.match_type = match_type;
    }

    public Long getRobot_id() {
        return robot_id;
    }

    public void setRobot_id(Long robot_id) {
        this.robot_id = robot_id;
    }

    public Long getEvent_id() {
        return event_id;
    }

    public void setEvent_id(Long event_id) {
        this.event_id = event_id;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public java.util.Date getLast_updated() {
        return last_updated;
    }

    public void setLast_updated(java.util.Date last_updated) {
        this.last_updated = last_updated;
    }

    /**
     * To-one relationship, resolved on first access.
     */
    @Generated
    public Robot getRobot() {
        Long __key = this.robot_id;
        if (robot__resolvedKey == null || !robot__resolvedKey.equals(__key)) {
            __throwIfDetached();
            RobotDao targetDao = daoSession.getRobotDao();
            Robot robotNew = targetDao.load(__key);
            synchronized (this) {
                robot = robotNew;
                robot__resolvedKey = __key;
            }
        }
        return robot;
    }

    @Generated
    public void setRobot(Robot robot) {
        synchronized (this) {
            this.robot = robot;
            robot_id = robot == null ? null : robot.getId();
            robot__resolvedKey = robot_id;
        }
    }

    /**
     * To-one relationship, resolved on first access.
     */
    @Generated
    public Event getEvent() {
        Long __key = this.event_id;
        if (event__resolvedKey == null || !event__resolvedKey.equals(__key)) {
            __throwIfDetached();
            EventDao targetDao = daoSession.getEventDao();
            Event eventNew = targetDao.load(__key);
            synchronized (this) {
                event = eventNew;
                event__resolvedKey = __key;
            }
        }
        return event;
    }

    @Generated
    public void setEvent(Event event) {
        synchronized (this) {
            this.event = event;
            event_id = event == null ? null : event.getId();
            event__resolvedKey = event_id;
        }
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
     * Entity must attached to an entity context.
     */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
     * Entity must attached to an entity context.
     */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
     * Entity must attached to an entity context.
     */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
