package com.team2052.frckrawler.models;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SERVER_LOG_ENTRY".
 */
@Entity
public class ServerLogEntry {
    private java.util.Date time;
    private String message;

    @Generated
    public ServerLogEntry() {
    }

    @Generated
    public ServerLogEntry(java.util.Date time, String message) {
        this.time = time;
        this.message = message;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
