package frckrawler;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import frckrawler.Game;
import frckrawler.Event;
import frckrawler.Team;
import frckrawler.User;
import frckrawler.Contact;
import frckrawler.Match;
import frckrawler.Robot;
import frckrawler.RobotEvent;
import frckrawler.Metric;
import frckrawler.RobotPhoto;
import frckrawler.MatchData;
import frckrawler.PitData;

import frckrawler.GameDao;
import frckrawler.EventDao;
import frckrawler.TeamDao;
import frckrawler.UserDao;
import frckrawler.ContactDao;
import frckrawler.MatchDao;
import frckrawler.RobotDao;
import frckrawler.RobotEventDao;
import frckrawler.MetricDao;
import frckrawler.RobotPhotoDao;
import frckrawler.MatchDataDao;
import frckrawler.PitDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gameDaoConfig;
    private final DaoConfig eventDaoConfig;
    private final DaoConfig teamDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig matchDaoConfig;
    private final DaoConfig robotDaoConfig;
    private final DaoConfig robotEventDaoConfig;
    private final DaoConfig metricDaoConfig;
    private final DaoConfig robotPhotoDaoConfig;
    private final DaoConfig matchDataDaoConfig;
    private final DaoConfig pitDataDaoConfig;

    private final GameDao gameDao;
    private final EventDao eventDao;
    private final TeamDao teamDao;
    private final UserDao userDao;
    private final ContactDao contactDao;
    private final MatchDao matchDao;
    private final RobotDao robotDao;
    private final RobotEventDao robotEventDao;
    private final MetricDao metricDao;
    private final RobotPhotoDao robotPhotoDao;
    private final MatchDataDao matchDataDao;
    private final PitDataDao pitDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gameDaoConfig = daoConfigMap.get(GameDao.class).clone();
        gameDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        teamDaoConfig = daoConfigMap.get(TeamDao.class).clone();
        teamDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        matchDaoConfig = daoConfigMap.get(MatchDao.class).clone();
        matchDaoConfig.initIdentityScope(type);

        robotDaoConfig = daoConfigMap.get(RobotDao.class).clone();
        robotDaoConfig.initIdentityScope(type);

        robotEventDaoConfig = daoConfigMap.get(RobotEventDao.class).clone();
        robotEventDaoConfig.initIdentityScope(type);

        metricDaoConfig = daoConfigMap.get(MetricDao.class).clone();
        metricDaoConfig.initIdentityScope(type);

        robotPhotoDaoConfig = daoConfigMap.get(RobotPhotoDao.class).clone();
        robotPhotoDaoConfig.initIdentityScope(type);

        matchDataDaoConfig = daoConfigMap.get(MatchDataDao.class).clone();
        matchDataDaoConfig.initIdentityScope(type);

        pitDataDaoConfig = daoConfigMap.get(PitDataDao.class).clone();
        pitDataDaoConfig.initIdentityScope(type);

        gameDao = new GameDao(gameDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);
        teamDao = new TeamDao(teamDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        matchDao = new MatchDao(matchDaoConfig, this);
        robotDao = new RobotDao(robotDaoConfig, this);
        robotEventDao = new RobotEventDao(robotEventDaoConfig, this);
        metricDao = new MetricDao(metricDaoConfig, this);
        robotPhotoDao = new RobotPhotoDao(robotPhotoDaoConfig, this);
        matchDataDao = new MatchDataDao(matchDataDaoConfig, this);
        pitDataDao = new PitDataDao(pitDataDaoConfig, this);

        registerDao(Game.class, gameDao);
        registerDao(Event.class, eventDao);
        registerDao(Team.class, teamDao);
        registerDao(User.class, userDao);
        registerDao(Contact.class, contactDao);
        registerDao(Match.class, matchDao);
        registerDao(Robot.class, robotDao);
        registerDao(RobotEvent.class, robotEventDao);
        registerDao(Metric.class, metricDao);
        registerDao(RobotPhoto.class, robotPhotoDao);
        registerDao(MatchData.class, matchDataDao);
        registerDao(PitData.class, pitDataDao);
    }
    
    public void clear() {
        gameDaoConfig.getIdentityScope().clear();
        eventDaoConfig.getIdentityScope().clear();
        teamDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        matchDaoConfig.getIdentityScope().clear();
        robotDaoConfig.getIdentityScope().clear();
        robotEventDaoConfig.getIdentityScope().clear();
        metricDaoConfig.getIdentityScope().clear();
        robotPhotoDaoConfig.getIdentityScope().clear();
        matchDataDaoConfig.getIdentityScope().clear();
        pitDataDaoConfig.getIdentityScope().clear();
    }

    public GameDao getGameDao() {
        return gameDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public TeamDao getTeamDao() {
        return teamDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public MatchDao getMatchDao() {
        return matchDao;
    }

    public RobotDao getRobotDao() {
        return robotDao;
    }

    public RobotEventDao getRobotEventDao() {
        return robotEventDao;
    }

    public MetricDao getMetricDao() {
        return metricDao;
    }

    public RobotPhotoDao getRobotPhotoDao() {
        return robotPhotoDao;
    }

    public MatchDataDao getMatchDataDao() {
        return matchDataDao;
    }

    public PitDataDao getPitDataDao() {
        return pitDataDao;
    }

}
