package frckrawler;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table MATCH_DATA.
 */
public class MatchDataDao extends AbstractDao<MatchData, Void>
{

    public static final String TABLENAME = "MATCH_DATA";
    private DaoSession daoSession;

    ;
    private String selectDeep;


    public MatchDataDao(DaoConfig config)
    {
        super(config);
    }

    public MatchDataDao(DaoConfig config, DaoSession daoSession)
    {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists)
    {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'MATCH_DATA' (" + //
                "'DATA' TEXT," + // 0: data
                "'ROBOT_ID' INTEGER," + // 1: robotId
                "'METRIC_ID' INTEGER," + // 2: metricId
                "'MATCH_ID' INTEGER);"); // 3: matchId
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists)
    {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MATCH_DATA'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, MatchData entity)
    {
        stmt.clearBindings();

        String data = entity.getData();
        if (data != null) {
            stmt.bindString(1, data);
        }

        Long robotId = entity.getRobotId();
        if (robotId != null) {
            stmt.bindLong(2, robotId);
        }

        Long metricId = entity.getMetricId();
        if (metricId != null) {
            stmt.bindLong(3, metricId);
        }

        Long matchId = entity.getMatchId();
        if (matchId != null) {
            stmt.bindLong(4, matchId);
        }
    }

    @Override
    protected void attachEntity(MatchData entity)
    {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Void readKey(Cursor cursor, int offset)
    {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    public MatchData readEntity(Cursor cursor, int offset)
    {
        MatchData entity = new MatchData( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // data
                cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // robotId
                cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // metricId
                cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // matchId
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, MatchData entity, int offset)
    {
        entity.setData(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setRobotId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMetricId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setMatchId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Void updateKeyAfterInsert(MatchData entity, long rowId)
    {
        // Unsupported or missing PK type
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Void getKey(MatchData entity)
    {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable()
    {
        return true;
    }

    protected String getSelectDeep()
    {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRobotDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMetricDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getMatchDao().getAllColumns());
            builder.append(" FROM MATCH_DATA T");
            builder.append(" LEFT JOIN ROBOT T0 ON T.'ROBOT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN METRIC T1 ON T.'METRIC_ID'=T1.'_id'");
            builder.append(" LEFT JOIN MATCH T2 ON T.'MATCH_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected MatchData loadCurrentDeep(Cursor cursor, boolean lock)
    {
        MatchData entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Robot robot = loadCurrentOther(daoSession.getRobotDao(), cursor, offset);
        entity.setRobot(robot);
        offset += daoSession.getRobotDao().getAllColumns().length;

        Metric metric = loadCurrentOther(daoSession.getMetricDao(), cursor, offset);
        entity.setMetric(metric);
        offset += daoSession.getMetricDao().getAllColumns().length;

        Match match = loadCurrentOther(daoSession.getMatchDao(), cursor, offset);
        entity.setMatch(match);

        return entity;
    }

    public MatchData loadDeep(Long key)
    {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[]{key.toString()};
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /**
     * Reads all available rows from the given cursor and returns a list of new ImageTO objects.
     */
    public List<MatchData> loadAllDeepFromCursor(Cursor cursor)
    {
        int count = cursor.getCount();
        List<MatchData> list = new ArrayList<MatchData>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<MatchData> loadDeepAllAndCloseCursor(Cursor cursor)
    {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }

    /**
     * A raw-style query where you can pass any WHERE clause and arguments.
     */
    public List<MatchData> queryDeep(String where, String... selectionArg)
    {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }

    /**
     * Properties of entity MatchData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties
    {
        public final static Property Data = new Property(0, String.class, "data", false, "DATA");
        public final static Property RobotId = new Property(1, Long.class, "robotId", false, "ROBOT_ID");
        public final static Property MetricId = new Property(2, Long.class, "metricId", false, "METRIC_ID");
        public final static Property MatchId = new Property(3, Long.class, "matchId", false, "MATCH_ID");
    }

}
