package com.team2052.frckrawler.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig matchDataDaoConfig;
    private final DaoConfig pitDataDaoConfig;
    private final DaoConfig matchCommentDaoConfig;
    private final DaoConfig robotEventDaoConfig;
    private final DaoConfig matchDaoConfig;
    private final DaoConfig eventDaoConfig;
    private final DaoConfig robotDaoConfig;
    private final DaoConfig metricDaoConfig;
    private final DaoConfig gameDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig teamDaoConfig;
    private final DaoConfig robotPhotoDaoConfig;
    private final DaoConfig userDaoConfig;

    private final MatchDataDao matchDataDao;
    private final PitDataDao pitDataDao;
    private final MatchCommentDao matchCommentDao;
    private final RobotEventDao robotEventDao;
    private final MatchDao matchDao;
    private final EventDao eventDao;
    private final RobotDao robotDao;
    private final MetricDao metricDao;
    private final GameDao gameDao;
    private final ContactDao contactDao;
    private final TeamDao teamDao;
    private final RobotPhotoDao robotPhotoDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        matchDataDaoConfig = daoConfigMap.get(MatchDataDao.class).clone();
        matchDataDaoConfig.initIdentityScope(type);

        pitDataDaoConfig = daoConfigMap.get(PitDataDao.class).clone();
        pitDataDaoConfig.initIdentityScope(type);

        matchCommentDaoConfig = daoConfigMap.get(MatchCommentDao.class).clone();
        matchCommentDaoConfig.initIdentityScope(type);

        robotEventDaoConfig = daoConfigMap.get(RobotEventDao.class).clone();
        robotEventDaoConfig.initIdentityScope(type);

        matchDaoConfig = daoConfigMap.get(MatchDao.class).clone();
        matchDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        robotDaoConfig = daoConfigMap.get(RobotDao.class).clone();
        robotDaoConfig.initIdentityScope(type);

        metricDaoConfig = daoConfigMap.get(MetricDao.class).clone();
        metricDaoConfig.initIdentityScope(type);

        gameDaoConfig = daoConfigMap.get(GameDao.class).clone();
        gameDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        teamDaoConfig = daoConfigMap.get(TeamDao.class).clone();
        teamDaoConfig.initIdentityScope(type);

        robotPhotoDaoConfig = daoConfigMap.get(RobotPhotoDao.class).clone();
        robotPhotoDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        matchDataDao = new MatchDataDao(matchDataDaoConfig, this);
        pitDataDao = new PitDataDao(pitDataDaoConfig, this);
        matchCommentDao = new MatchCommentDao(matchCommentDaoConfig, this);
        robotEventDao = new RobotEventDao(robotEventDaoConfig, this);
        matchDao = new MatchDao(matchDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);
        robotDao = new RobotDao(robotDaoConfig, this);
        metricDao = new MetricDao(metricDaoConfig, this);
        gameDao = new GameDao(gameDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        teamDao = new TeamDao(teamDaoConfig, this);
        robotPhotoDao = new RobotPhotoDao(robotPhotoDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(MatchData.class, matchDataDao);
        registerDao(PitData.class, pitDataDao);
        registerDao(MatchComment.class, matchCommentDao);
        registerDao(RobotEvent.class, robotEventDao);
        registerDao(Match.class, matchDao);
        registerDao(Event.class, eventDao);
        registerDao(Robot.class, robotDao);
        registerDao(Metric.class, metricDao);
        registerDao(Game.class, gameDao);
        registerDao(Contact.class, contactDao);
        registerDao(Team.class, teamDao);
        registerDao(RobotPhoto.class, robotPhotoDao);
        registerDao(User.class, userDao);
    }

    public void clear() {
        matchDataDaoConfig.getIdentityScope().clear();
        pitDataDaoConfig.getIdentityScope().clear();
        matchCommentDaoConfig.getIdentityScope().clear();
        robotEventDaoConfig.getIdentityScope().clear();
        matchDaoConfig.getIdentityScope().clear();
        eventDaoConfig.getIdentityScope().clear();
        robotDaoConfig.getIdentityScope().clear();
        metricDaoConfig.getIdentityScope().clear();
        gameDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        teamDaoConfig.getIdentityScope().clear();
        robotPhotoDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public MatchDataDao getMatchDataDao() {
        return matchDataDao;
    }

    public PitDataDao getPitDataDao() {
        return pitDataDao;
    }

    public MatchCommentDao getMatchCommentDao() {
        return matchCommentDao;
    }

    public RobotEventDao getRobotEventDao() {
        return robotEventDao;
    }

    public MatchDao getMatchDao() {
        return matchDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public RobotDao getRobotDao() {
        return robotDao;
    }

    public MetricDao getMetricDao() {
        return metricDao;
    }

    public GameDao getGameDao() {
        return gameDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public TeamDao getTeamDao() {
        return teamDao;
    }

    public RobotPhotoDao getRobotPhotoDao() {
        return robotPhotoDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
