package com.team2052.frckrawler.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MATCH_COMMENT.
 */
public class MatchComment implements java.io.Serializable {

    private Long id;
    private Long matchId;
    private Long robotId;
    private Long eventId;
    private String comment;

    public MatchComment() {
    }

    public MatchComment(Long id) {
        this.id = id;
    }

    public MatchComment(Long id, Long matchId, Long robotId, Long eventId, String comment) {
        this.id = id;
        this.matchId = matchId;
        this.robotId = robotId;
        this.eventId = eventId;
        this.comment = comment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMatchId() {
        return matchId;
    }

    public void setMatchId(Long matchId) {
        this.matchId = matchId;
    }

    public Long getRobotId() {
        return robotId;
    }

    public void setRobotId(Long robotId) {
        this.robotId = robotId;
    }

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
