package com.team2052.frckrawler.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table PICK_LIST.
 */
public class PickList {

    private Long id;
    private String name;
    private Long eventId;
    private String data;

    public PickList() {
    }

    public PickList(Long id) {
        this.id = id;
    }

    public PickList(Long id, String name, Long eventId, String data) {
        this.id = id;
        this.name = name;
        this.eventId = eventId;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
