package com.team2052.frckrawler.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table PIT_DATA.
 */
public class PitDataDao extends AbstractDao<PitData, Long> {

    public static final String TABLENAME = "PIT_DATA";
    private Query<PitData> event_PitDataListQuery;

    ;
    private Query<PitData> robot_PitDataListQuery;
    private Query<PitData> metric_PitDataListQuery;
    private Query<PitData> user_PitDataListQuery;

    public PitDataDao(DaoConfig config) {
        super(config);
    }

    public PitDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'PIT_DATA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROBOT_ID' INTEGER NOT NULL ," + // 1: robot_id
                "'METRIC_ID' INTEGER NOT NULL ," + // 2: metric_id
                "'EVENT_ID' INTEGER NOT NULL ," + // 3: event_id
                "'USER_ID' INTEGER NOT NULL ," + // 4: user_id
                "'DATA' TEXT);"); // 5: data
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PIT_DATA'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    public PitData readEntity(Cursor cursor, int offset) {
        PitData entity = new PitData( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // robot_id
                cursor.getLong(offset + 2), // metric_id
                cursor.getLong(offset + 3), // event_id
                cursor.getLong(offset + 4), // user_id
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // data
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, PitData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRobot_id(cursor.getLong(offset + 1));
        entity.setMetric_id(cursor.getLong(offset + 2));
        entity.setEvent_id(cursor.getLong(offset + 3));
        entity.setUser_id(cursor.getLong(offset + 4));
        entity.setData(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, PitData entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRobot_id());
        stmt.bindLong(3, entity.getMetric_id());
        stmt.bindLong(4, entity.getEvent_id());
        stmt.bindLong(5, entity.getUser_id());

        String data = entity.getData();
        if (data != null) {
            stmt.bindString(6, data);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(PitData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(PitData entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Internal query to resolve the "pitDataList" to-many relationship of Event.
     */
    public List<PitData> _queryEvent_PitDataList(long event_id) {
        synchronized (this) {
            if (event_PitDataListQuery == null) {
                QueryBuilder<PitData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Event_id.eq(null));
                event_PitDataListQuery = queryBuilder.build();
            }
        }
        Query<PitData> query = event_PitDataListQuery.forCurrentThread();
        query.setParameter(0, event_id);
        return query.list();
    }

    /**
     * Internal query to resolve the "pitDataList" to-many relationship of Robot.
     */
    public List<PitData> _queryRobot_PitDataList(long robot_id) {
        synchronized (this) {
            if (robot_PitDataListQuery == null) {
                QueryBuilder<PitData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Robot_id.eq(null));
                robot_PitDataListQuery = queryBuilder.build();
            }
        }
        Query<PitData> query = robot_PitDataListQuery.forCurrentThread();
        query.setParameter(0, robot_id);
        return query.list();
    }

    /**
     * Internal query to resolve the "pitDataList" to-many relationship of Metric.
     */
    public List<PitData> _queryMetric_PitDataList(long metric_id) {
        synchronized (this) {
            if (metric_PitDataListQuery == null) {
                QueryBuilder<PitData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Metric_id.eq(null));
                metric_PitDataListQuery = queryBuilder.build();
            }
        }
        Query<PitData> query = metric_PitDataListQuery.forCurrentThread();
        query.setParameter(0, metric_id);
        return query.list();
    }

    /**
     * Internal query to resolve the "pitDataList" to-many relationship of User.
     */
    public List<PitData> _queryUser_PitDataList(long user_id) {
        synchronized (this) {
            if (user_PitDataListQuery == null) {
                QueryBuilder<PitData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.User_id.eq(null));
                user_PitDataListQuery = queryBuilder.build();
            }
        }
        Query<PitData> query = user_PitDataListQuery.forCurrentThread();
        query.setParameter(0, user_id);
        return query.list();
    }

    /**
     * Properties of entity PitData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Robot_id = new Property(1, long.class, "robot_id", false, "ROBOT_ID");
        public final static Property Metric_id = new Property(2, long.class, "metric_id", false, "METRIC_ID");
        public final static Property Event_id = new Property(3, long.class, "event_id", false, "EVENT_ID");
        public final static Property User_id = new Property(4, long.class, "user_id", false, "USER_ID");
        public final static Property Data = new Property(5, String.class, "data", false, "DATA");
    }

}
